function negativeLogLikelihoods = calNegativeLogLikelihoodGPU(obj, ...
    cys, cxs, ...
    oObjG, oProbG, ...
    cbeds1BeatG, maskFLikelihoodG)
    % cys/cxs: (nSpotsParallel, 1) coordinates of the spots
    % oObj/oProb: handle objects of the class cObj/cProbe
    % cbeds1BeatG (nYX, nYX, nSpotsParallel)
    % maskFLikelihoodG % (nYX, nYX), GPU, mask fourier space in calLikelihoodGPU
    % [out]: negativeLogLikelihoods (nSpotsParallel, 1)
    
    obj.multisliceForwardingGPU(cys, cxs, oObjG, oProbG);

    % calculate the negative log-likelihoods
    negativeLogLikelihoods = gather( ...
        reshape( ...
        sum(maskFLikelihoodG .* (sqrt(cbeds1BeatG) - sqrt(obj.cbedsCalG)).^2, [1 2]), ...
        obj.nSpotsParallel, 1) ...
        );
end

